# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_auto_20171003_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='activation_key',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='key_expires',
        ),
    ]
