# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_auto_20171004_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
