# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_auto_20171003_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
