# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0012_remove_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 14, 16, 26, 13, 165689, tzinfo=utc)),
        ),
    ]
